### PR TITLE
fix: handle unicode in lexer

### LINKED ISSUE #184: lexer: No token found at position
the error was thrown in `pg_lexer` when testing #172 on [this file](https://github.com/psteinroe/supabase-cache-helpers/blob/6d84a63dd63cc0d636dbd4f3d188d9ac8ad460aa/supabase/migrations/1660333326_test_schema.sql). we should fix this.

### PR DESCRIPTION
**Pull request by psteinroe**
fixes #184 

also using `TextSize` now. but we might want to revisit the lexer at some point because I dont think we should store the text in the tokens anymore.

### CODE REVIEW

File: crates/pg_lexer/src/lib.rs [hunk 1]
```diff
@@ -119,25 +119,24 @@ pub fn lex(text: &str) -> Vec<Token> {
...
-                .take(
-                    usize::try_from(pg_query_token.end).unwrap()
-                        - usize::try_from(pg_query_token.start).unwrap(),
-                )
-                .collect();
-            let len = token_text.len();
+
+            // the lexer returns byte indices, so we need to slice
+            let token_text = &text[usize::try_from(pg_query_token.start).unwrap()
+                ..usize::try_from(pg_query_token.end).unwrap()];
```
Comment (psteinroe) [inline crates/pg_lexer/src/lib.rs:132]: the important change is this

**Review by juleswritescode — APPROVED** [review]
Nice!
